baseURL = 'https://notes.pgersl.xyz/'
languageCode = 'cs-CZ'
title = 'Petr Geršl - Notes'
uglyURLs = 'false'
enableEmoji = 'true'
[markup]
    [markup.goldmark.renderer]
        unsafe = 'true'
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1
[params]
    description = "The official website of Petr Geršl dedicated to his notes and research"
[outputs]
    home = ['HTML', 'JSON', 'RSS']
    page = ['HTML']
[frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    expiryDate = ['expiryDate']
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
[menu]
    [[menu.sites]]
        identifier = "main"
        name = "Hlavní"
        url = "https://pgersl.xyz"
        weight = 1
    [[menu.sites]]
        identifier = "wiki"
        name = "Wiki"
        url = "https://wiki.pgersl.xyz"
        weight = 2
    [[menu.sites]]
        identifier = "notes"
        name = "Hudba"
        url = "https://music.pgersl.xyz"
        weight = 3